apiVersion: v1
kind: Service
metadata:
  name: {{ include "heimq.fullname" . }}
  labels:
    {{- include "heimq.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: kafka
      protocol: TCP
    {{- if .Values.heimq.metrics.enabled }}
    - name: metrics
      port: {{ .Values.heimq.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "heimq.selectorLabels" . | nindent 4 }}
